### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by WaliedWeb** [WaliedWeb/capstone-project#3]
## Value proposition

**As a** user
**I need** to add my memories
**to be able to** create a diary from them

## Description (text, scribbles, images, designs)

<img width="402" alt="Bildschirmfoto 2021-11-22 um 14 31 13" src="https://user-images.githubusercontent.com/91471710/142870381-94b4902a-b9d8-4de5-a510-2d4373deb609.png">

## Acceptance Criteria

- [ ] All inputs are required 
- [ ] max. 50 characters
- [ ] The destination and memories should never overlap in the list
- [ ] The list should scroll vertically on overflow

## Tasks (for developers)

- [ ] Create feature branch
- [ ] Form component
- [ ] Button component
