### ISSUE TITLE
Delete card

### ISSUE THREAD

**Issue by WaliedWeb** [WaliedWeb/capstone-project#4]
## Value proposition

**As a** user
**I need** to delete my memories
**to be able to** restructure my card

## Description (text, scribbles, images, designs)

<img width="406" alt="Bildschirmfoto 2021-11-22 um 15 51 17" src="https://user-images.githubusercontent.com/91471710/142883134-62f46408-741a-4a17-acbf-f122f0573dab.png">

## Acceptance Criteria

- [ ] The button schould be round

## Tasks (for developers)

- [ ] Create feature branch
- [ ] Button delete component
- [ ] The color should be red
